version: '3.8'

services:
  example:
    image: httpd:alpine
    container_name: example
    restart: unless-stopped
    ports: [80:80]
    volumes:
      - ./www:/usr/local/apache2/htdocs:ro
      - ./scripts/patch.sh:/docker-entrypoint.d/patch.sh:ro
    entrypoint: ["/bin/sh", "-c", "/bin/sh /docker-entrypoint.d/patch.sh && /usr/local/bin/httpd-foreground"]