name: Create a new bundle

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3
      # Create the bundle
      - name: Create a new bundle directory
        run: mkdir -p bundle
      - name: Copy all the files and folders to the bundle directory
        run: mv docker-compose.yml scripts/ www/ bundle/
      - name: Upload the compressed archive to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: example
          path: bundle
          if-no-files-found: error
